### ISSUE TITLE
Prevent loss of edited pages without saving

### ISSUE THREAD

**Issue by CarlaHofmann** [CarlaHofmann/exercise-generator-fe#35]
If pages are closed in edited state without saving, an option should be implemented to not lose them.

Opton 1: Pop-up window when closing pages that were not saved with the request whether you really want to close them.

Option 2: Tasks / Sheets are saved as drafts.

**Comment by CarlaHofmann** [comment]
Decision: Pop-up

**Comment by MatrixTheAssembler** [comment]
Gibt es für exercises, von da übernehmen. CanDeactivateComponent beachten
